var data = {
   "Thing":{
      "Event":{
         "EducationEvent":"test",
         "UserInteraction":{
            "UserLikes":"another test",
            "UserCheckins":1,
            "UserPlusOnes":1,
            "UserTweets":1,
            "UserBlocks":1,
            "UserDownloads":1,
            "UserPlays":1,
            "UserComments":1,
            "UserPageVisits":1
         },
         "MusicEvent":1,
         "DanceEvent":1,
         "Festival":1,
         "SportsEvent":1,
         "SocialEvent":1,
         "VisualArtsEvent":1,
         "TheaterEvent":1,
         "BusinessEvent":1,
         "FoodEvent":1,
         "SaleEvent":1,
         "ComedyEvent":1,
         "LiteraryEvent":1,
         "ChildrensEvent":1
      },
      "Place":{
         "CivicStructure":{
            "FireStation":1,
            "GovernmentBuilding":{
               "DefenceEstablishment":1,
               "LegislativeBuilding":1,
               "Embassy":1,
               "Courthouse":1,
               "CityHall":1
            },
            "BusStation":1,
            "Aquarium":1,
            "ParkingFacility":1,
            "Playground":1,
            "MovieTheater":1,
            "MusicVenue":1,
            "PerformingArtsTheater":1,
            "Crematorium":1,
            "Park":1,
            "Museum":1,
            "Airport":1,
            "SubwayStation":1,
            "PoliceStation":1,
            "Hospital":1,
            "Zoo":1,
            "TaxiStand":1,
            "PlaceOfWorship":{
               "BuddhistTemple":1,
               "Synagogue":1,
               "CatholicChurch":1,
               "HinduTemple":1,
               "Church":1,
               "Mosque":1
            },
            "StadiumOrArena":1,
            "TrainStation":1,
            "BusStop":1,
            "Beach":1,
            "RVPark":1,
            "Cemetery":1,
            "EventVenue":1,
            "Campground":1
         },
         "LocalBusiness":{
            "AutomotiveBusiness":{
               "AutoRepair":1,
               "GasStation":1,
               "AutoPartsStore":1,
               "AutoBodyShop":1,
               "MotorcycleRepair":1,
               "MotorcycleDealer":1,
               "AutoDealer":1,
               "AutoWash":1,
               "AutoRental":1
            },
            "LodgingBusiness":{
               "Motel":1,
               "Hostel":1,
               "BedAndBreakfast":1,
               "Hotel":1
            },
            "ChildCare":1,
            "Library":1,
            "EmploymentAgency":1,
            "RecyclingCenter":1,
            "EntertainmentBusiness":{
               "AdultEntertainment":1,
               "MovieTheater":1,
               "AmusementPark":1,
               "ComedyClub":1,
               "NightClub":1,
               "ArtGallery":1,
               "Casino":1
            },
            "InternetCafe":1,
            "AnimalShelter":1,
            "ShoppingCenter":1,
            "FinancialService":{
               "InsuranceAgency":1,
               "BankOrCreditUnion":1,
               "AutomatedTeller":1,
               "AccountingService":1
            },
            "Store":{
               "HobbyShop":1,
               "DepartmentStore":1,
               "HardwareStore":1,
               "OfficeEquipmentStore":1,
               "SportingGoodsStore":1,
               "ShoeStore":1,
               "WholesaleStore":1,
               "MovieRentalStore":1,
               "GroceryStore":1,
               "HomeGoodsStore":1,
               "ConvenienceStore":1,
               "Florist":1,
               "ComputerStore":1,
               "MensClothingStore":1,
               "PetStore":1,
               "ToyStore":1,
               "BikeStore":1,
               "GardenStore":1,
               "TireShop":1,
               "JewelryStore":1,
               "AutoPartsStore":1,
               "PawnShop":1,
               "FurnitureStore":1,
               "LiquorStore":1,
               "MobilePhoneStore":1,
               "MusicStore":1,
               "BookStore":1,
               "OutletStore":1,
               "ClothingStore":1,
               "ElectronicsStore":1
            },
            "SportsActivityLocation":{
               "ExerciseGym":1,
               "SkiResort":1,
               "HealthClub":1,
               "BowlingAlley":1,
               "PublicSwimmingPool":1,
               "SportsClub":1,
               "StadiumOrArena":1,
               "TennisComplex":1,
               "GolfCourse":1
            },
            "MedicalOrganization":{
               "Pharmacy":1,
               "Physician":1,
               "Optician":1,
               "MedicalClinic":1,
               "VeterinaryCare":1,
               "Hospital":1,
               "Dentist":1
            },
            "HealthAndBeautyBusiness":{
               "HairSalon":1,
               "HealthClub":1,
               "TattooParlor":1,
               "NailSalon":1,
               "DaySpa":1,
               "BeautySalon":1
            },
            "SelfStorage":1,
            "FoodEstablishment":{
               "BarOrPub":1,
               "FastFoodRestaurant":1,
               "Restaurant":1,
               "CafeOrCoffeeShop":1,
               "IceCreamShop":1,
               "Brewery":1,
               "Winery":1,
               "Bakery":1
            },
            "TelevisionStation":1,
            "EmergencyService":{
               "FireStation":1,
               "PoliceStation":1,
               "Hospital":1
            },
            "GovernmentOffice":{
               "PostOffice":1
            },
            "TravelAgency":1,
            "ProfessionalService":{
               "GeneralContractor":1,
               "Electrician":1,
               "RoofingContractor":1,
               "Attorney":1,
               "AccountingService":1,
               "Dentist":1,
               "Notary":1,
               "Plumber":1,
               "HousePainter":1,
               "Locksmith":1
            },
            "DryCleaningOrLaundry":1,
            "TouristInformationCenter":1,
            "RealEstateAgent":1,
            "RadioStation":1,
            "HomeAndConstructionBusiness":{
               "GeneralContractor":1,
               "Electrician":1,
               "RoofingContractor":1,
               "MovingCompany":1,
               "HVACBusiness":1,
               "Plumber":1,
               "HousePainter":1,
               "Locksmith":1
            }
         },
         "LandmarksOrHistoricalBuildings":1,
         "AdministrativeArea":{
            "State":1,
            "City":1,
            "Country":1
         },
         "Residence":{
            "SingleFamilyResidence":1,
            "GatedResidenceCommunity":1,
            "ApartmentComplex":1
         },
         "Landform":{
            "Mountain":1,
            "Continent":1,
            "Volcano":1,
            "BodyOfWater":{
               "LakeBodyOfWater":1,
               "RiverBodyOfWater":1,
               "SeaBodyOfWater":1,
               "Reservoir":1,
               "OceanBodyOfWater":1,
               "Pond":1,
               "Canal":1,
               "Waterfall":1
            }
         },
         "TouristAttraction":1
      },
      "Person":1,
      "Property":1,
      "Product":1,
      "Type":1,
      "Intangible":{
         "Offer":{
            "AggregateOffer":1
         },
         "Quantity":{
            "Mass":1,
            "Distance":1,
            "Duration":1
         },
         "Language":1,
         "Rating":{
            "AggregateRating":1
         },
         "Enumeration":{
            "OfferItemCondition":1,
            "BookFormatType":1,
            "ItemAvailability":1
         },
         "StructuredValue":{
            "NutritionInformation":1,
            "ContactPoint":{
               "PostalAddress":1
            },
            "GeoCoordinates":1
         }
      },
      "Organization":{
         "PerformingGroup":{
            "MusicGroup":1,
            "DanceGroup":1,
            "TheaterGroup":1
         },
         "GovernmentOrganization":1,
         "SportsTeam":1,
         "NGO":1,
         "EducationalOrganization":{
            "HighSchool":1,
            "Preschool":1,
            "MiddleSchool":1,
            "CollegeOrUniversity":1,
            "ElementarySchool":1,
            "School":1
         },
         "Corporation":1
      },
      "CreativeWork":{
         "MusicPlaylist":{
            "MusicAlbum":1
         },
         "Photograph":1,
         "Sculpture":1,
         "Article":{
            "NewsArticle":1,
            "BlogPosting":1,
            "ScholarlyArticle":1
         },
         "WebPageElement":{
            "SiteNavigationElement":1,
            "Table":1,
            "WPAdBlock":1,
            "WPHeader":1,
            "WPFooter":1,
            "WPSideBar":1
         },
         "TVSeries":1,
         "Painting":1,
         "Movie":1,
         "Book":1,
         "MediaObject":{
            "MusicVideoObject":1,
            "AudioObject":1,
            "VideoObject":1,
            "ImageObject":1
         },
         "Blog":1,
         "ItemList":1,
         "TVEpisode":1,
         "Review":1,
         "Map":1,
         "WebPage":{
            "ProfilePage":1,
            "ContactPage":1,
            "AboutPage":1,
            "SearchResultsPage":1,
            "CollectionPage":{
               "ImageGallery":1,
               "VideoGallery":1
            },
            "ItemPage":1,
            "CheckoutPage":1
         },
         "TVSeason":1,
         "Recipe":1,
         "MusicRecording":1
      }
   },
   "DataType":{
      "Date":1,
      "Text":{
         "URL":1
      },
      "Number":{
         "Float":1,
         "Integer":1
      },
      "Boolean":1
   }
}
